### ISSUE TITLE
Implement Printable Permission Slip

### ISSUE THREAD

**Issue by DonnOMalley** [DonnOMalley/OnlinePermissionSlips#14]
- [ ] Guardian
- [x] Teacher
- [x] School/System Admin?

**Comment by DonnOMalley** [comment]
Created - Accessible from Search Page of permission slips. Not available to Guardians. If they can access the page, they should submit their approval electronically.

**Comment by skootchingdog** [comment]
Test teacher, works fine.

**Comment by DonnOMalley** [comment]
Guardian Printing is not MVP. Will revisit as customer requirements demands
