### ISSUE TITLE
Guardian Profile Edit - Last and middle names not actually updated.  

### ISSUE THREAD

**Issue by skootchingdog** [DonnOMalley/OnlinePermissionSlips#21]
Doesn't show immediately or after email confirmation.

Tested on PSparent3 (email parent3@tps).  Logged in, changed middle initial and edited last name.  Changes not shown immediately in profile, or after confirmation email received and confirmed.

**Comment by DonnOMalley** [comment]
Unable to reproduce. I did have a couple other errors with the email (shouldn't have sent the confirmation unless changing emails) but that's all published and available now. 

Could be a refresh issue but not positive. Retest and let me know.

**Comment by skootchingdog** [comment]
Retested, no issue.
